from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import WheelWorldWorld


ITEM_NAME_TO_ID: dict[str, int] = {
    "Black Biplane": 100,
    "Booster Seat": 101,
    "Bumper Bike": 102,
    "Corp Bars": 103,
    "Corp Fork": 104,
    "Corp Frame": 105,
    "Corp Saddle": 106,
    "Corp Train": 107,
    "Corp Wheel": 108,
    "Cross Frame Black": 109,
    "Jumper Seat": 110,
    "Tall Bars": 111,
    "Tri Frame Teal": 112,
    "Jump Fork": 113,
    "Jump Saddle": 114,
    "Jump Wheels": 115,
    "Legendary Fork": 116,
    "Legendary Frame": 117,
    "Legendary Handlebars": 118,
    "Legendary Saddle": 119,
    "Legendary Train": 120,
    "Legendary Wheels": 121,
    "Angled Train": 122,
    "Vintage Train": 123,
    "Light Train": 124,
    "Thick Train": 125,
    "Cutout Train": 126,
    "Hollow Train": 127,
    "Baby Train": 128,
    "Clutch Train": 129,
    "Chainless Train": 130,
    "Horse Train": 131,
    "Ancient Fork": 132,
    "Fin Fork": 133,
    "Fork Fork": 134,
    "Mudder Fork": 135,
    "Horse Fork": 136,
    "Elasto Fork": 137,
    "Vintage Fork": 138,
    "Basic Fork": 139,
    "Simpleton Fork": 140,
    "Springy Fork": 141,
    "Wood Fork": 142,
    "Ancient Frame": 143,
    "Wood Frame": 144,
    "Step Frame": 145,
    "Truck Frame": 146,
    "Highwater Frame": 147,
    "Aero Frame": 148,
    "Bamboo Frame": 149,
    "Layup Frame": 150,
    "Decobike Frame": 151,
    "Double Trouble Frame": 152,
    "Feline Frame": 153,
    "Horse Frame": 154,
    "Weenie Frame": 155,
    "Leisure Frame": 156,
    "Lunar Rim Frame": 157,
    "Ol Tubey Frame": 158,
    "Paperboy Frame": 159,
    "Quad Frame": 160,
    "Flagship Frame": 161,
    "Simpleton Frame": 162,
    "Slammer Frame": 163,
    "Smoothie Frame": 164,
    "Paperclip Frame": 165,
    "Swoosh Frame": 166,
    "Third Wheel Frame": 167,
    "Tucked Frame": 168,
    "Trad Frame": 169,
    "Vanilla Frame": 170,
    "Drop Frame": 171,
    "Bent Frame": 172,
    "Deep Drops": 173,
    "Lil Sweep Bars": 174,
    "Ergo Bars": 175,
    "Ape Bars": 176,
    "Paperboy Bars": 177,
    "Ancient Bars": 178,
    "Leisure Bars": 179,
    "Moustache Bars": 180,
    "Streamers Bars": 181,
    "Wood Bars": 182,
    "Gamer Bars": 183,
    "Antlers Bars": 184,
    "Bullhorn Bars": 185,
    "Horns Bars": 186,
    "Dad Bars": 187,
    "Ears Bars": 188,
    "Horse Bars": 189,
    "Lane Splitter Bars": 190,
    "Moto Bars": 191,
    "Pursuit Bars": 192,
    "Speeder Bars": 193,
    "Simpleton Bars": 194,
    "Wide Bars": 195,
    "01 Train Small": 196,
    "07 Train Gear2": 197,
    "Mini Wheel": 198,
    "1 Saddle": 199,
    "Paperboy Saddle": 200,
    "Tilt Saddle": 201,
    "Banana Saddle": 202,
    "Boomerang Saddle": 203,
    "Rivets Saddle": 204,
    "Ancient Saddle": 205,
    "Gamer Saddle": 206,
    "Hole Saddle": 207,
    "Horse Saddle": 208,
    "Needle Saddle": 209,
    "Simpleton Saddle": 210,
    "Buttercup Saddle": 211,
    "Wood Saddle": 212,
    "Quad Spoke Wheel": 213,
    "Blade Wheel": 214,
    "Ancient Wheel": 215,
    "Deep V Wheel": 216,
    "Eye Wheel": 217,
    "Handy Wheel": 218,
    "Horse Wheel": 219,
    "Lawnmower Wheel": 220,
    "Speed Wheel": 221,
    "Stars Wheel": 222,
    "Tan Wall Wheel": 223,
    "Wood Wheel": 224,
    "Body Bars": 225,
    "Body Fork": 226,
    "Body Frame": 227,
    "Body Saddle": 228,
    "Body Train": 229,
    "Body Wheels": 230,
    "Bolt Frame": 231,
    "Wheed Whacker": 232,
    "Thornbush": 233,
    "Coasting Train": 234,
    "La Cucaracha": 235,
    "Drift Wheels": 236,
    "The Heavy": 237,
    "Part Perceiver": 238,
    "Light Fork": 239,
    "Light Frame": 240,
    "Sweet Bars": 241,
    "Sweet Fork": 242,
    "Sweet Frame": 243,
    "Sweet Saddle": 244,
    "Sweet Train": 245,
    "Sweet Wheels": 246,
    "Recharge Wheels": 247,
    "Flag Finder": 248,
    "Ramp Rummager": 249,
    "Package Perceiver": 250,
    "Secret Searcher": 251,
    "The Straight Edge": 252,
    "Terrain Wheel": 253,
    "The Uproad": 254,
    "Uphiller": 255,
    "Green Thumbs": 256,
    "Wicked Bars": 257,
    "Wicked Fork": 258,
    "Wicked Frame": 259,
    "Wicked Saddle": 260,
    "Wicked Train": 261,
    "Wicked Wheel": 262,
    "Speeder Fork": 263,
    "The Speed Engine": 264,
    "Speeder Saddle": 265,
    "Speeder Train": 266,
    "Speeder Wheel": 267,
    "Synthetic Fork": 268,
    "Synthetic Frame": 269,
    "Synthetic Handlebars": 270,
    "Synthetic Saddle": 271,
    "Synthetic Train": 272,
    "Synthetic Wheels": 273,
    "Commuter Bars": 274,
    "Commuter Frame": 275,
    "Commuter Train": 276,
    "Commuter Wheel": 277,
    "Rusty Bars": 278,
    "Rusty Fork": 279,
    "Rusty Frame": 280,
    "Rusty Seat": 281,
    "Rusty Train": 282,
    "Rusty Wheel": 283,
    "Trudge Wheel": 284,
    "Amateur Bars": 285,
    "Amateur Fork": 286,
    "Amateur Frame": 287,
    "Amateur Saddle": 288,
    "Amateur Train": 289,
    "Amateur Wheel": 290,
    "Quick Bars": 291,
    "Quick Fork": 292,
    "Quick Frame": 293,
    "Quick Saddle": 294,
    "Quick Train": 295,
    "Quick Wheel": 296,
    "Tight Bars": 297,
    "Tight Fork": 298,
    "Tight Frame": 299,
    "Tight Seat": 300,
    "Tight Train": 301,
    "Tight Wheel": 302,
    "Sand Pipers": 303,
    "Drift Fork": 304,
    "Heavy Fork": 305,
    "Ace Bars": 306,
    "Ace Fork": 307,
    "Ace Frame": 308,
    "Ace Saddle": 309,
    "Ace Train": 310,
    "Ace Wheels": 311,
    "Jet Bars": 312,
    "Jet Fork": 313,
    "Jet Frame": 314,
    "Jet Saddle": 315,
    "Jet Train": 316,
    "Jet Wheel": 317,
    "Pilot Bars": 318,
    "Pilot Fork": 319,
    "Pilot Frame": 320,
    "Pilot Saddle": 321,
    "Pilot Train": 322,
    "Pilot Wheel": 323,
    "Train 01": 324,
    "Trick Bars": 325,
    "Trick Fork": 326,
    "Trick Frame": 327,
    "Trick Saddle": 328,
    "Trick Train": 329,
    "Trick Wheel": 330,
}


LEGENDARY_PARTS: set[str] = {
    "Legendary Fork",
    "Legendary Frame",
    "Legendary Handlebars",
    "Legendary Saddle",
    "Legendary Train",
    "Legendary Wheels",
}

SYNTHETIC_PARTS: set[str] = {
    "Synthetic Fork",
    "Synthetic Frame",
    "Synthetic Handlebars",
    "Synthetic Saddle",
    "Synthetic Train",
    "Synthetic Wheels",
}


class WheelWorldItem(Item):
    game = "Wheel World"


# Items pre-placed at specific locations or excluded from the pool (starting gear, cut content).
LOCKED_ITEMS: set[str] = {
    "Commuter Wheel",
    "Handy Wheel", "Ears Bars", "Bullhorn Bars", "Tilt Saddle", "Fin Fork", "Part Perceiver", 
    "07 Train Gear2", "Mini Wheel", "Secret Searcher", "Stars Wheel", "The Uproad", "Mudder Fork",
    "01 Train Small",
    "Rusty Bars", "Rusty Fork", "Rusty Frame", "Rusty Seat", "Rusty Train", "Rusty Wheel",
}


def create_item(world: WheelWorldWorld, name: str) -> WheelWorldItem:
    if name in LEGENDARY_PARTS or name in SYNTHETIC_PARTS or name in LOCKED_ITEMS:
        classification = ItemClassification.progression
    else:
        classification = ItemClassification.useful
    return WheelWorldItem(name, classification, ITEM_NAME_TO_ID[name], world.player)


def create_all_items(world: WheelWorldWorld) -> None:
    number_of_locations = len(world.multiworld.get_unfilled_locations(world.player))

    # Progression items must always be in the pool.
    progression_names = sorted(LEGENDARY_PARTS | SYNTHETIC_PARTS)
    itempool: list[Item] = [world.create_item(name) for name in progression_names]

    # Fill remaining slots with other bike parts, chosen randomly.
    # Locked items are excluded — they are pre-placed or starting gear.
    other_names = [
        name for name in ITEM_NAME_TO_ID
        if name not in LEGENDARY_PARTS and name not in SYNTHETIC_PARTS and name not in LOCKED_ITEMS
    ]
    world.random.shuffle(other_names)
    remaining_slots = number_of_locations - len(itempool)
    for name in other_names[:remaining_slots]:
        itempool.append(world.create_item(name))

    world.multiworld.itempool += itempool
