from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import ItemClassification, Location

from .items import WheelWorldItem

if TYPE_CHECKING:
    from .world import WheelWorldWorld


LOCATION_NAME_TO_ID: dict[str, int] = {
    "The Grumpy Grimpeurs": 100,
    "The Nude Dudes": 101,
    "Cliffhangers": 102,
    "The Bikepackeurs": 103,
    "The Corner Kings": 104,
    "The Sales Team": 105,
    "The Replacements": 106,
    "The World Tourers": 107,
    "The Lords of the Land": 108,
    "The Underbikeurs": 109,
    "The Regulars": 110,
    "Le Grand Crew": 111,
    "The Explorers": 112,
    "The Survivors": 113,
    "The Pedal Assistants": 114,
    "The Paceline Cooks": 115,
    "The Sommoliers": 116,
    "The Pedal Pumpers": 117,
    "The Heroica": 118,
    "Lunardo Hill Boys": 119,
    "The Gravel Privateers": 120,
    "The Locals": 121,
    "The Celebrities": 122,
    "The Practice": 123,
    "The Vintage Grinder": 124,
    "The Collectors": 125,
    "Lunardo Hill Boys Rematch": 126,
    "The Pub Crawlers": 127,
    "The Commuters": 128,
    "The Fixies": 129,
    "The Handlebaristas": 130,
    "The Shimmy Squad": 131,
    "The Rocket - 1": 133,
    "The Rocket - 2": 134,
    "The Rocket - 3": 135,
    "Rooster's Rando - 1": 136,
    "Rooster's Rando - 2": 137,
    "Rooster's Rando - 3": 138,
    "The Smokestack - 1": 139,
    "The Smokestack - 2": 140,
    "Mark I GigaBike Exhibition Race - 1": 141,
    "Mark I GigaBike Exhibition Race - 2": 142,
    "Mark I GigaBike Exhibition Race - 3": 143,
    "Mark I GigaBike Exhibition Race - 4": 144,
    "Mark I GigaBike Exhibition Race - 5": 145,
    "Mark I GigaBike Exhibition Race - 6": 146,
    "The Doyenne - 1": 147,
    "The Doyenne - 2": 148,
    "Lunardo Hills Dead End Cliff Box": 150,
    "Field South of Rooster Statue Box": 151,
    "Vineyard Roadside Double Car Box": 152,
    "Well Near Sommoliers Box": 153,
    "Preserves Stonehenge Box": 154,
    "Preserves Pedal Pumpers Campsite Box": 155,
    "Vineyard Field East of Le Grand Crew Box": 156,
    "Farmland Rooster Statue Box": 157,
    "Redwoods Lighthouse Box": 158,
    "Vineyard Bellshrine Town Box": 159,
    "Farmlands West Portal Potty House to the South Box": 160,
    "Chuck's House Box": 161,
    "Lunardo Hill Lookout Box": 162,
    "Behind Underbikeurs House Box": 163,
    "East Velo City Roadside Box": 164,
    "Redwoods On Log Near Bikepackeurs Campsite Box": 165,
    "Farmland City Alley Box": 166,
    "Lunardo Hill Component Dave Box": 167,
    "Lunardo Hill Bridge Lookout Box": 168,
    "Doyenne Box": 169,
    "Vineyard N+1 Guy Near Vintage Grinder Box": 170,
    "Farmland Ruins Below The Ramp Box": 171,
    "Lunardo Hill Boys Beach Box": 172,
    "Southeast Farmlands Well Box": 173,
    "Lunardo Hill Bridge Jump Box": 174,
    "North Redwoods Jump Log Box": 175,
    "Bikepackeurs Campsite Box": 176,
    "Vineyard By The Bell Box": 177,
    "Farmland By The Locals Box": 178,
    "Sommaliers Tactics Boy Box": 179,
    "East of Gravel Privateers Field Box": 180,
    "Velo City to Preserves Fork in the Road Box": 181,
    "Vineyard Field Between Boss Race and Bell Box": 182,
    "Vineyards Recovery Field Dude Box": 183,
    "Farmlands West Portal Potty House to the East Box": 184,
    "Lunardo Island Forest Box": 185,
    "Handlebaristas Box": 186,
    "East Velo City Alley Box": 187,
    "South of Preserves Cyclorp Box": 188,
    "Central Farmland Northeast Of Portal Potty Box": 189,
    "Farmland City West": 190,
    "West Velo City Party Pace Guy Box": 191,
    "Le Grand Crew House Box": 192,
    "Preserves Velodrome Box": 193,
    "Farmland Ruins Wall Ramp Box": 194,
    "Vineyard Between Two Houses Box": 195,
    "Vineyard Portal Potty Roundabout Box": 196,
    "Vineyard Secret Track Truck Box": 197,
    "Farmlands South Portal Potty Box": 198,
    "Vineyard Donut Secret Track Box": 199,
    "Redwoods Near Biomechanics Guy Box": 200,
    "Pedal Assistants Box": 201,
    "Velo City Near The Corner Kings Box": 202,
    "Velo City By The Practice Box": 203,
    "Farmland West Potty Box": 204,
    "North Farmland Potty Ramp Box": 205,
    "Vineyard Redwood Roundabout Box": 206,
    "Near Cliffhangers Box": 207,
    "Vineyard Bellshrine Field Ramp Box": 208,
    "Vineyard Roadside Car and Tent Box": 209,
    "Gravel Privateers House Box": 210,
    "Behind The Pedal Pumpers Box": 211,
    "Farmlands South of Bell Shrine Box": 212,
    "Northwest Warehouse Lost Boy Box": 213,
    "Port Corp-Shop-Roof-To-Containers Box": 214,
    "Warehouse Secret Shop Box": 215,
    "Southwest Wasteland Outside of Dump Box": 216,
    "Port Roof Above Corp Shop Box": 217,
    "Warehouse Platform North Side Box": 218,
    "Port Triple Building Roof Box": 219,
    "East Port Shipping Containers Box": 220,
    "Paceline Cooks Box": 221,
    "Southeast Dump Shipping Container Box": 222,
    "Wasteland Broken Bridge Box": 223,
    "Big Drill South of Warehouse Portal Potty Box": 224,
    "North Port Between Two Trucks Box": 225,
    "Warehouse Great Deals On Used Cars Box": 226,
    "Wasteland City Northwest Box": 227,
    "South Port On Top Of Containers Box": 228,
    "Wasteland City Southeast Box": 229,
    "Southeast Port Behind Ramp Box": 230,
    "Warehouse Big Drill Outside Platform Box": 231,
    "Wasteland Under Broken Bridge Box": 232,
    "Port On Top Of Container Near Silo Box": 233,
    "Warehouse Bell Shrine Box": 234,
    "Wasteland Dump Among the Pipes Box": 235,
    "Wasteland Outside Mount Send Box": 236,
    "Wasteland Center City Under Underpass Box": 237,
    "Warehouse Platform West Side Box": 238,
    "Wasteland Bridge Near Mount Send Box": 239,
    "Wasteland City Bell Shrine Box": 240,
    "Junkyard Pond Shipping Container Box": 241,
    "Steel Wheelman Box": 242,
    "West Port On Top Of Shipping Container Box": 243,
    "Southeast Dump Peninsula Box": 244,
    "Warehouse Fork Outside Big Platform Box": 245,
    "Warehouse North Portal Potty Box": 246,
    "Northeast Port Warehouse Box": 247,
    "Mount Send East Box": 248,
    "Mount Send West Box": 249,
    "Corp shop - Part #1": 250,
    "Corp shop - Part #2": 251,
    "Corp shop - Part #3": 252,
    "Corp shop - Part #4": 253,
    "Corp shop - Part #5": 254,
    "Corp shop - Part #6": 255,
    "Corp shop - Part #7": 256,
    "Corp shop - Part #8": 257,
    "Corp shop - Part #9": 258,
    "Corp shop - Part #10": 259,
    "Corp shop - Part #11": 260,
    "Corp shop - Part #12": 261,
    "Junkyard govt shop - Part #1": 262,
    "Junkyard govt shop - Part #2": 263,
    "Wasteland Shop (Flea) Variant - Part #1": 264,
    "Wasteland Shop (Flea) Variant - Part #2": 265,
    "Wasteland Shop (Flea) Variant - Part #3": 266,
    "Wasteland Shop (Flea) Variant - Part #4": 267,
    "Wasteland Shop (Flea) Variant - Part #5": 268,
    "Wasteland Shop (Flea) Variant - Part #6": 269,
    "Sequoias Govt Shop - Part #1": 270,
    "Sequoias Govt Shop - Part #2": 271,
    "Sequoias Govt Shop - Part #3": 272,
    "Sequoias Govt Shop - Part #4": 273,
    "Vineyards coast shop - Part #1": 274,
    "Vineyards coast shop - Part #2": 275,
    "Vineyards coast shop - Part #3": 276,
    "Vineyards coast shop - Part #4": 277,
    "Vineyards coast shop - Part #5": 278,
    "Vineyards coast shop - Part #6": 279,
    "Vineyards coast shop - Part #7": 280,
    "Pink Shop - Part #1": 281,
    "Pink Shop - Part #2": 282,
    "Pink Shop - Part #3": 283,
    "Pink Shop - Part #4": 284,
    "Pink Shop - Part #5": 285,
    "Hot Dog shop - Part #1": 286,
    "Hot Dog shop - Part #2": 287,
    "Plant Shop - Part #1": 288,
    "Plant Shop - Part #2": 289,
    "Plant Shop - Part #3": 290,
    "Plant Shop - Part #4": 291,
    "Entry Plaza Shop - Part #1": 292,
    "Entry Plaza Shop - Part #2": 293,
    "Entry Plaza Shop - Part #3": 294,
    "Hub Shop 2 - Part #1": 295,
    "Hub Shop 2 - Part #2": 296,
    "Hub Shop 2 - Part #3": 297,
    "Hub Shop 2 - Part #4": 298,
    "Daves bike shop - Part #1": 299,
    "Daves bike shop - Part #2": 300,
    "Daves bike shop - Part #3": 301,
    "Daves bike shop - Part #4": 302,
    "Daves bike shop - Part #5": 303,
    "Daves bike shop - Part #6": 304,
    "Daves bike shop - Part #7": 305,
    "Daves bike shop - Part #8": 306,
    "Daves bike shop - Part #9": 307,
    "Mount Send Shop (Flea) Variant - Part #1": 308,
    "Mount Send Shop (Flea) Variant - Part #2": 309,
    "Mount Send Shop (Flea) Variant - Part #3": 310,
}


LOCATION_SCENE: dict[str, str] = {
    "The Grumpy Grimpeurs": "Tramonto",
    "The Nude Dudes": "Wasteland",
    "Cliffhangers": "Tramonto",
    "The Bikepackeurs": "Tramonto",
    "The Corner Kings": "Tramonto",
    "The Sales Team": "Wasteland",
    "The Replacements": "Wasteland",
    "The World Tourers": "Wasteland",
    "The Lords of the Land": "Wasteland",
    "The Underbikeurs": "Tramonto",
    "The Regulars": "Tramonto",
    "Le Grand Crew": "Tramonto",
    "The Explorers": "Wasteland",
    "The Survivors": "Wasteland",
    "The Pedal Assistants": "Tramonto",
    "The Paceline Cooks": "Wasteland",
    "The Sommoliers": "Tramonto",
    "The Pedal Pumpers": "Tramonto",
    "The Heroica": "Wasteland",
    "Lunardo Hill Boys": "Lunardo Island",
    "The Gravel Privateers": "Tramonto",
    "The Locals": "Tramonto",
    "The Celebrities": "Wasteland",
    "The Practice": "Tramonto",
    "The Vintage Grinder": "Tramonto",
    "The Collectors": "Wasteland",
    "Lunardo Hill Boys Rematch": "Tramonto",
    "The Pub Crawlers": "Tramonto",
    "The Commuters": "Tramonto",
    "The Fixies": "Tramonto",
    "The Handlebaristas": "Tramonto",
    "The Shimmy Squad": "Tramonto",
    "The Rocket - 1": "Tramonto",
    "The Rocket - 2": "Tramonto",
    "The Rocket - 3": "Tramonto",
    "Rooster's Rando - 1": "Tramonto",
    "Rooster's Rando - 2": "Tramonto",
    "Rooster's Rando - 3": "Tramonto",
    "The Smokestack - 1": "Tramonto",
    "The Smokestack - 2": "Tramonto",
    "Mark I GigaBike Exhibition Race - 1": "Wasteland",
    "Mark I GigaBike Exhibition Race - 2": "Wasteland",
    "Mark I GigaBike Exhibition Race - 3": "Wasteland",
    "Mark I GigaBike Exhibition Race - 4": "Wasteland",
    "Mark I GigaBike Exhibition Race - 5": "Wasteland",
    "Mark I GigaBike Exhibition Race - 6": "Wasteland",
    "The Doyenne - 1": "Tramonto",
    "The Doyenne - 2": "Tramonto",
    "Lunardo Hills Dead End Cliff Box": "Tramonto",
    "Field South of Rooster Statue Box": "Tramonto",
    "Vineyard Roadside Double Car Box": "Tramonto",
    "Well Near Sommoliers Box": "Tramonto",
    "Preserves Stonehenge Box": "Tramonto",
    "Preserves Pedal Pumpers Campsite Box": "Tramonto",
    "Vineyard Field East of Le Grand Crew Box": "Tramonto",
    "Farmland Rooster Statue Box": "Tramonto",
    "Redwoods Lighthouse Box": "Tramonto",
    "Vineyard Bellshrine Town Box": "Tramonto",
    "Farmlands West Portal Potty House to the South Box": "Tramonto",
    "Chuck's House Box": "Lunardo Island",
    "Lunardo Hill Lookout Box": "Tramonto",
    "Behind Underbikeurs House Box": "Tramonto",
    "East Velo City Roadside Box": "Tramonto",
    "Redwoods On Log Near Bikepackeurs Campsite Box": "Tramonto",
    "Farmland City Alley Box": "Tramonto",
    "Lunardo Hill Component Dave Box": "Tramonto",
    "Lunardo Hill Bridge Lookout Box": "Tramonto",
    "Doyenne Box": "Tramonto",
    "Vineyard N+1 Guy Near Vintage Grinder Box": "Tramonto",
    "Farmland Ruins Below The Ramp Box": "Tramonto",
    "Lunardo Hill Boys Beach Box": "Lunardo Island",
    "Southeast Farmlands Well Box": "Tramonto",
    "Lunardo Hill Bridge Jump Box": "Tramonto",
    "North Redwoods Jump Log Box": "Tramonto",
    "Bikepackeurs Campsite Box": "Tramonto",
    "Vineyard By The Bell Box": "Tramonto",
    "Farmland By The Locals Box": "Tramonto",
    "Sommaliers Tactics Boy Box": "Tramonto",
    "East of Gravel Privateers Field Box": "Tramonto",
    "Velo City to Preserves Fork in the Road Box": "Tramonto",
    "Vineyard Field Between Boss Race and Bell Box": "Tramonto",
    "Vineyards Recovery Field Dude Box": "Tramonto",
    "Farmlands West Portal Potty House to the East Box": "Tramonto",
    "Lunardo Island Forest Box": "Lunardo Island",
    "Handlebaristas Box": "Tramonto",
    "East Velo City Alley Box": "Tramonto",
    "South of Preserves Cyclorp Box": "Tramonto",
    "Central Farmland Northeast Of Portal Potty Box": "Tramonto",
    "Farmland City West": "Tramonto",
    "West Velo City Party Pace Guy Box": "Tramonto",
    "Le Grand Crew House Box": "Tramonto",
    "Preserves Velodrome Box": "Tramonto",
    "Farmland Ruins Wall Ramp Box": "Tramonto",
    "Vineyard Between Two Houses Box": "Tramonto",
    "Vineyard Portal Potty Roundabout Box": "Tramonto",
    "Vineyard Secret Track Truck Box": "Tramonto",
    "Farmlands South Portal Potty Box": "Tramonto",
    "Vineyard Donut Secret Track Box": "Tramonto",
    "Redwoods Near Biomechanics Guy Box": "Tramonto",
    "Pedal Assistants Box": "Tramonto",
    "Velo City Near The Corner Kings Box": "Tramonto",
    "Velo City By The Practice Box": "Tramonto",
    "Farmland West Potty Box": "Tramonto",
    "North Farmland Potty Ramp Box": "Tramonto",
    "Vineyard Redwood Roundabout Box": "Tramonto",
    "Near Cliffhangers Box": "Tramonto",
    "Vineyard Bellshrine Field Ramp Box": "Tramonto",
    "Vineyard Roadside Car and Tent Box": "Tramonto",
    "Gravel Privateers House Box": "Tramonto",
    "Behind The Pedal Pumpers Box": "Tramonto",
    "Farmlands South of Bell Shrine Box": "Tramonto",
    "Northwest Warehouse Lost Boy Box": "Wasteland",
    "Port Corp-Shop-Roof-To-Containers Box": "Wasteland",
    "Warehouse Secret Shop Box": "Wasteland",
    "Southwest Wasteland Outside of Dump Box": "Wasteland",
    "Port Roof Above Corp Shop Box": "Wasteland",
    "Warehouse Platform North Side Box": "Wasteland",
    "Port Triple Building Roof Box": "Wasteland",
    "East Port Shipping Containers Box": "Wasteland",
    "Paceline Cooks Box": "Wasteland",
    "Southeast Dump Shipping Container Box": "Wasteland",
    "Wasteland Broken Bridge Box": "Wasteland",
    "Big Drill South of Warehouse Portal Potty Box": "Wasteland",
    "North Port Between Two Trucks Box": "Wasteland",
    "Warehouse Great Deals On Used Cars Box": "Wasteland",
    "Wasteland City Northwest Box": "Wasteland",
    "South Port On Top Of Containers Box": "Wasteland",
    "Wasteland City Southeast Box": "Wasteland",
    "Southeast Port Behind Ramp Box": "Wasteland",
    "Warehouse Big Drill Outside Platform Box": "Wasteland",
    "Wasteland Under Broken Bridge Box": "Wasteland",
    "Port On Top Of Container Near Silo Box": "Wasteland",
    "Warehouse Bell Shrine Box": "Wasteland",
    "Wasteland Dump Among the Pipes Box": "Wasteland",
    "Wasteland Outside Mount Send Box": "Wasteland",
    "Wasteland Center City Under Underpass Box": "Wasteland",
    "Warehouse Platform West Side Box": "Wasteland",
    "Wasteland Bridge Near Mount Send Box": "Wasteland",
    "Wasteland City Bell Shrine Box": "Wasteland",
    "Junkyard Pond Shipping Container Box": "Wasteland",
    "Steel Wheelman Box": "Wasteland",
    "West Port On Top Of Shipping Container Box": "Wasteland",
    "Southeast Dump Peninsula Box": "Wasteland",
    "Warehouse Fork Outside Big Platform Box": "Wasteland",
    "Warehouse North Portal Potty Box": "Wasteland",
    "Northeast Port Warehouse Box": "Wasteland",
    "Mount Send East Box": "Mount Send",
    "Mount Send West Box": "Mount Send",
    "Corp shop - Part #1": "Wasteland",
    "Corp shop - Part #2": "Wasteland",
    "Corp shop - Part #3": "Wasteland",
    "Corp shop - Part #4": "Wasteland",
    "Corp shop - Part #5": "Wasteland",
    "Corp shop - Part #6": "Wasteland",
    "Corp shop - Part #7": "Wasteland",
    "Corp shop - Part #8": "Wasteland",
    "Corp shop - Part #9": "Wasteland",
    "Corp shop - Part #10": "Wasteland",
    "Corp shop - Part #11": "Wasteland",
    "Corp shop - Part #12": "Wasteland",
    "Junkyard govt shop - Part #1": "Wasteland",
    "Junkyard govt shop - Part #2": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #1": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #2": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #3": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #4": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #5": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #6": "Wasteland",
    "Sequoias Govt Shop - Part #1": "Tramonto",
    "Sequoias Govt Shop - Part #2": "Tramonto",
    "Sequoias Govt Shop - Part #3": "Tramonto",
    "Sequoias Govt Shop - Part #4": "Tramonto",
    "Vineyards coast shop - Part #1": "Tramonto",
    "Vineyards coast shop - Part #2": "Tramonto",
    "Vineyards coast shop - Part #3": "Tramonto",
    "Vineyards coast shop - Part #4": "Tramonto",
    "Vineyards coast shop - Part #5": "Tramonto",
    "Vineyards coast shop - Part #6": "Tramonto",
    "Vineyards coast shop - Part #7": "Tramonto",
    "Pink Shop - Part #1": "Tramonto",
    "Pink Shop - Part #2": "Tramonto",
    "Pink Shop - Part #3": "Tramonto",
    "Pink Shop - Part #4": "Tramonto",
    "Pink Shop - Part #5": "Tramonto",
    "Hot Dog shop - Part #1": "Tramonto",
    "Hot Dog shop - Part #2": "Tramonto",
    "Plant Shop - Part #1": "Tramonto",
    "Plant Shop - Part #2": "Tramonto",
    "Plant Shop - Part #3": "Tramonto",
    "Plant Shop - Part #4": "Tramonto",
    "Entry Plaza Shop - Part #1": "Tramonto",
    "Entry Plaza Shop - Part #2": "Tramonto",
    "Entry Plaza Shop - Part #3": "Tramonto",
    "Hub Shop 2 - Part #1": "Tramonto",
    "Hub Shop 2 - Part #2": "Tramonto",
    "Hub Shop 2 - Part #3": "Tramonto",
    "Hub Shop 2 - Part #4": "Tramonto",
    "Daves bike shop - Part #1": "Tramonto",
    "Daves bike shop - Part #2": "Tramonto",
    "Daves bike shop - Part #3": "Tramonto",
    "Daves bike shop - Part #4": "Tramonto",
    "Daves bike shop - Part #5": "Tramonto",
    "Daves bike shop - Part #6": "Tramonto",
    "Daves bike shop - Part #7": "Tramonto",
    "Daves bike shop - Part #8": "Tramonto",
    "Daves bike shop - Part #9": "Tramonto",
    "Mount Send Shop (Flea) Variant - Part #1": "Mount Send",
    "Mount Send Shop (Flea) Variant - Part #2": "Mount Send",
    "Mount Send Shop (Flea) Variant - Part #3": "Mount Send",
}


class WheelWorldLocation(Location):
    game = "Wheel World"


def create_all_locations(world: WheelWorldWorld) -> None:
    for name, scene in LOCATION_SCENE.items():
        region = world.get_region(scene)
        loc = WheelWorldLocation(world.player, name, LOCATION_NAME_TO_ID[name], region)
        region.locations.append(loc)

    create_events(world)


def create_events(world: WheelWorldWorld) -> None:
    from .items import ITEM_NAME_TO_ID

    beach_box = world.get_location("Lunardo Hill Boys Beach Box")
    commuter_wheel = WheelWorldItem(
        "Commuter Wheel", ItemClassification.progression, ITEM_NAME_TO_ID["Commuter Wheel"], world.player
    )
    beach_box.place_locked_item(commuter_wheel)

    mountain = world.get_region("Mount Send")
    event_location = WheelWorldLocation(world.player, "Perform The Great Shift", None, mountain)
    event_item = WheelWorldItem("Victory", ItemClassification.progression, None, world.player)
    event_location.place_locked_item(event_item)
    mountain.locations.append(event_location)
