from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import ItemClassification, Location

from .items import WheelWorldItem

if TYPE_CHECKING:
    from .world import WheelWorldWorld


LOCATION_NAME_TO_ID: dict[str, int] = {
    "The Grumpy Grimpeurs": 100,
    "The Nude Dudes": 101,
    "Cliffhangers": 102,
    "The Bikepackeurs": 103,
    "The Corner Kings": 104,
    "The Sales Team": 105,
    "The Replacements": 106,
    "The World Tourers": 107,
    "The Lords of the Land": 108,
    "The Underbikeurs": 109,
    "The Regulars": 110,
    "Le Grand Crew": 111,
    "The Explorers": 112,
    "The Survivors": 113,
    "The Pedal Assistants": 114,
    "The Paceline Cooks": 115,
    "The Sommoliers": 116,
    "The Pedal Pumpers": 117,
    "The Heroica": 118,
    "Lunardo Hill Boys": 119,
    "The Gravel Privateers": 120,
    "The Locals": 121,
    "The Celebrities": 122,
    "The Practice": 123,
    "The Vintage Grinder": 124,
    "The Collectors": 125,
    "Lunardo Hill Boys Rematch": 126,
    "The Pub Crawlers": 127,
    "The Commuters": 128,
    "The Fixies": 129,
    "The Handlebaristas": 130,
    "The Shimmy Squad": 131,
    "The K.O.B": 132,
    "The Rocket - 1": 133,
    "The Rocket - 2": 134,
    "The Rocket - 3": 135,
    "Rooster's Rando - 1": 136,
    "Rooster's Rando - 2": 137,
    "Rooster's Rando - 3": 138,
    "The Smokestack - 1": 139,
    "The Smokestack - 2": 140,
    "Mark I GigaBike Exhibition Race - 1": 141,
    "Mark I GigaBike Exhibition Race - 2": 142,
    "Mark I GigaBike Exhibition Race - 3": 143,
    "Mark I GigaBike Exhibition Race - 4": 144,
    "Mark I GigaBike Exhibition Race - 5": 145,
    "Mark I GigaBike Exhibition Race - 6": 146,
    "The Doyenne - 1": 147,
    "The Doyenne - 2": 148,
    "Race Stub Extravaganza": 149,
    "Lunardo Hills Dead End Cliff Box": 150,
    "PLACEHOLDER_1": 151,
    "Vineyard Roadside Double Car Box": 152,
    "Well Near Sommoliers Box": 153,
    "PLACEHOLDER_4": 154,
    "PLACEHOLDER_5": 155,
    "PLACEHOLDER_6": 156,
    "Farmland Rooster Statue Box": 157,
    "Redwoods Lighthouse Box": 158,
    "Vineyard Bellshrine Town Box": 159,
    "Farmland Behind The West Oranges Barn Box": 160,
    "Chuck's House Box": 161,
    "Lunardo Hill Lookout Box": 162,
    "Behind Underbikeurs House Box": 163,
    "East Velo City Roadside Box": 164,
    "Redwoods On Log Near Bikepackeurs Campsite Box": 165,
    "Farmland City Alley Box": 166,
    "Lunardo Hill Component Dave Box": 167,
    "Lunardo Hill Bridge Lookout Box": 168,
    "Doyenne Box": 169,
    "Vineyard N+1 Guy Near Vintage Grinder Box": 170,
    "Farmland Ruins Below The Ramp Box": 171,
    "Lunardo Hill Boys Beach Box": 172,
    "Southeast Farmlands Well Box": 173,
    "Lunardo Hill Bridge Jump Box": 174,
    "North Redwoods Jump Log Box": 175,
    "Bikepackeurs Campsite Box": 176,
    "Vineyard By The Bell Box": 177,
    "PLACEHOLDER_28": 178,
    "Sommaliers Tactics Boy Box": 179,
    "East of Gravel Privateers Field Box": 180,
    "PLACEHOLDER_31": 181,
    "PLACEHOLDER_32": 182,
    "PLACEHOLDER_33": 183,
    "Farmland Behind The East Oranges Barn Box": 184,
    "Lunardo Island Forest Box": 185,
    "Handlebaristas Box": 186,
    "East Velo City Alley Box": 187,
    "PLACEHOLDER_38": 188,
    "PLACEHOLDER_39": 189,
    "Farmland City West": 190,
    "West Velo City Party Pace Guy Box": 191,
    "Le Grand Crew House Box": 192,
    "PLACEHOLDER_43": 193,
    "Farmland Ruins Wall Ramp Box": 194,
    "Vineyard Between Two Houses Box": 195,
    "Vineyard Portal Potty Roundabout Box": 196,
    "Vineyards Secret Track Truck Box": 197,
    "PLACEHOLDER_48": 198,
    "PLACEHOLDER_49": 199,
    "Redwoods Near Biomechanics Guy Box": 200,
    "PLACEHOLDER_51": 201,
    "Velo City Near The Corner Kings Box": 202,
    "Velo City By The Practice Box": 203,
    "PLACEHOLDER_54": 204,
    "North Farmland Potty Ramp Box": 205,
    "Vineyard Redwood Roundabout Box": 206,
    "Near Cliffhangers Box": 207,
    "Vineyard Bellshrine Field Ramp Box": 208,
    "Vineyard Roadside Car and Tent Box": 209,
    "Gravel Privateers House Box": 210,
    "Behind The Pedal Pumpers Box": 211,
    "PLACEHOLDER_62": 212,
    "PLACEHOLDER_63": 213,
    "PLACEHOLDER_64": 214,
    "PLACEHOLDER_65": 215,
    "PLACEHOLDER_66": 216,
    "PLACEHOLDER_67": 217,
    "PLACEHOLDER_68": 218,
    "PLACEHOLDER_69": 219,
    "PLACEHOLDER_70": 220,
    "PLACEHOLDER_71": 221,
    "PLACEHOLDER_72": 222,
    "PLACEHOLDER_73": 223,
    "PLACEHOLDER_74": 224,
    "PLACEHOLDER_75": 225,
    "PLACEHOLDER_76": 226,
    "PLACEHOLDER_77": 227,
    "PLACEHOLDER_78": 228,
    "PLACEHOLDER_79": 229,
    "PLACEHOLDER_80": 230,
    "PLACEHOLDER_81": 231,
    "PLACEHOLDER_82": 232,
    "PLACEHOLDER_83": 233,
    "PLACEHOLDER_84": 234,
    "PLACEHOLDER_85": 235,
    "PLACEHOLDER_86": 236,
    "PLACEHOLDER_87": 237,
    "PLACEHOLDER_88": 238,
    "PLACEHOLDER_89": 239,
    "PLACEHOLDER_90": 240,
    "PLACEHOLDER_91": 241,
    "PLACEHOLDER_92": 242,
    "PLACEHOLDER_93": 243,
    "PLACEHOLDER_94": 244,
    "PLACEHOLDER_95": 245,
    "PLACEHOLDER_96": 246,
    "PLACEHOLDER_97": 247,
    "PLACEHOLDER_98": 248,
    "PLACEHOLDER_99": 249,
    "Corp shop - Part #1": 250,
    "Corp shop - Part #2": 251,
    "Corp shop - Part #3": 252,
    "Corp shop - Part #4": 253,
    "Corp shop - Part #5": 254,
    "Corp shop - Part #6": 255,
    "Corp shop - Part #7": 256,
    "Corp shop - Part #8": 257,
    "Corp shop - Part #9": 258,
    "Corp shop - Part #10": 259,
    "Corp shop - Part #11": 260,
    "Corp shop - Part #12": 261,
    "Junkyard govt shop - Part #1": 262,
    "Junkyard govt shop - Part #2": 263,
    "Wasteland Shop (Flea) Variant - Part #1": 264,
    "Wasteland Shop (Flea) Variant - Part #2": 265,
    "Wasteland Shop (Flea) Variant - Part #3": 266,
    "Wasteland Shop (Flea) Variant - Part #4": 267,
    "Wasteland Shop (Flea) Variant - Part #5": 268,
    "Wasteland Shop (Flea) Variant - Part #6": 269,
    "Sequoias Govt Shop - Part #1": 270,
    "Sequoias Govt Shop - Part #2": 271,
    "Sequoias Govt Shop - Part #3": 272,
    "Sequoias Govt Shop - Part #4": 273,
    "Vineyards coast shop - Part #1": 274,
    "Vineyards coast shop - Part #2": 275,
    "Vineyards coast shop - Part #3": 276,
    "Vineyards coast shop - Part #4": 277,
    "Vineyards coast shop - Part #5": 278,
    "Vineyards coast shop - Part #6": 279,
    "Vineyards coast shop - Part #7": 280,
    "Pink Shop - Part #1": 281,
    "Pink Shop - Part #2": 282,
    "Pink Shop - Part #3": 283,
    "Pink Shop - Part #4": 284,
    "Pink Shop - Part #5": 285,
    "Hot Dog shop - Part #1": 286,
    "Hot Dog shop - Part #2": 287,
    "Plant Shop - Part #1": 288,
    "Plant Shop - Part #2": 289,
    "Plant Shop - Part #3": 290,
    "Plant Shop - Part #4": 291,
    "Entry Plaza Shop - Part #1": 292,
    "Entry Plaza Shop - Part #2": 293,
    "Entry Plaza Shop - Part #3": 294,
    "Hub Shop 2 - Part #1": 295,
    "Hub Shop 2 - Part #2": 296,
    "Hub Shop 2 - Part #3": 297,
    "Hub Shop 2 - Part #4": 298,
    "Daves bike shop - Part #1": 299,
    "Daves bike shop - Part #2": 300,
    "Daves bike shop - Part #3": 301,
    "Daves bike shop - Part #4": 302,
    "Daves bike shop - Part #5": 303,
    "Daves bike shop - Part #6": 304,
    "Daves bike shop - Part #7": 305,
    "Daves bike shop - Part #8": 306,
    "Daves bike shop - Part #9": 307,
    "Mount Send Shop (Flea) Variant - Part #1": 308,
    "Mount Send Shop (Flea) Variant - Part #2": 309,
    "Mount Send Shop (Flea) Variant - Part #3": 310,
}


LOCATION_SCENE: dict[str, str] = {
    "The Grumpy Grimpeurs": "Tramonto",
    "The Nude Dudes": "Wasteland",
    "Cliffhangers": "Tramonto",
    "The Bikepackeurs": "Tramonto",
    "The Corner Kings": "Tramonto",
    "The Sales Team": "Wasteland",
    "The Replacements": "Wasteland",
    "The World Tourers": "Wasteland",
    "The Lords of the Land": "Wasteland",
    "The Underbikeurs": "Tramonto",
    "The Regulars": "Tramonto",
    "Le Grand Crew": "Tramonto",
    "The Explorers": "Wasteland",
    "The Survivors": "Wasteland",
    "The Pedal Assistants": "Tramonto",
    "The Paceline Cooks": "Wasteland",
    "The Sommoliers": "Tramonto",
    "The Pedal Pumpers": "Tramonto",
    "The Heroica": "Wasteland",
    "Lunardo Hill Boys": "Lunardo Island",
    "The Gravel Privateers": "Tramonto",
    "The Locals": "Tramonto",
    "The Celebrities": "Wasteland",
    "The Practice": "Tramonto",
    "The Vintage Grinder": "Tramonto",
    "The Collectors": "Wasteland",
    "Lunardo Hill Boys Rematch": "Tramonto",
    "The Pub Crawlers": "Tramonto",
    "The Commuters": "Tramonto",
    "The Fixies": "Tramonto",
    "The Handlebaristas": "Tramonto",
    "The Shimmy Squad": "Tramonto",
    "The K.O.B": "Mount Send", #I have no idea where this one is, so I'm putting it in the last area
    "The Rocket - 1": "Tramonto",
    "The Rocket - 2": "Tramonto",
    "The Rocket - 3": "Tramonto",
    "Rooster's Rando - 1": "Tramonto",
    "Rooster's Rando - 2": "Tramonto",
    "Rooster's Rando - 3": "Tramonto",
    "The Smokestack - 1": "Tramonto",
    "The Smokestack - 2": "Tramonto",
    "Mark I GigaBike Exhibition Race - 1": "Wasteland",
    "Mark I GigaBike Exhibition Race - 2": "Wasteland",
    "Mark I GigaBike Exhibition Race - 3": "Wasteland",
    "Mark I GigaBike Exhibition Race - 4": "Wasteland",
    "Mark I GigaBike Exhibition Race - 5": "Wasteland",
    "Mark I GigaBike Exhibition Race - 6": "Wasteland",
    "The Doyenne - 1": "Tramonto",
    "The Doyenne - 2": "Tramonto",
    "Race Stub Extravaganza": "Mount Send",
    "Lunardo Hills Dead End Cliff Box": "Tramonto",
    "PLACEHOLDER_1": "Tramonto",
    "Vineyard Roadside Double Car Box": "Tramonto",
    "Well Near Sommoliers Box": "Tramonto",
    "PLACEHOLDER_4": "Tramonto",
    "PLACEHOLDER_5": "Tramonto",
    "PLACEHOLDER_6": "Tramonto",
    "Farmland Rooster Statue Box": "Tramonto",
    "Redwoods Lighthouse Box": "Tramonto",
    "PLACEHOLDER_9": "Tramonto",
    "Farmland Behind The West Oranges Barn Box": "Tramonto",
    "Chuck's House Box": "Lunardo Island",
    "Lunardo Hill Lookout Box": "Tramonto",
    "Behind Underbikeurs House Box": "Tramonto",
    "East Velo City Roadside Box": "Tramonto",
    "Redwoods On Log Near Bikepackeurs Campsite Box": "Tramonto",
    "Farmland City Alley Box": "Tramonto",
    "Lunardo Hill Component Dave Box": "Tramonto",
    "Lunardo Hill Bridge Lookout Box": "Tramonto",
    "Doyenne Box": "Tramonto",
    "Vineyard N+1 Guy Near Vintage Grinder Box": "Tramonto",
    "Farmland Ruins Below The Ramp Box": "Tramonto",
    "Lunardo Hill Boys Beach Box": "Lunardo Island",
    "Southeast Farmlands Well Box": "Tramonto",
    "Lunardo Hill Bridge Jump Box": "Tramonto",
    "North Redwoods Jump Log Box": "Tramonto",
    "Bikepackeurs Campsite Box": "Tramonto",
    "Vineyard By The Bell Box": "Tramonto",
    "PLACEHOLDER_28": "Tramonto",
    "Sommaliers Tactics Boy Box": "Tramonto",
    "East of Gravel Privateers Field Box": "Tramonto",
    "PLACEHOLDER_31": "Tramonto",
    "PLACEHOLDER_32": "Tramonto",
    "PLACEHOLDER_33": "Tramonto",
    "Farmland Behind The East Oranges Barn Box": "Tramonto",
    "Lunardo Island Forest Box": "Lunardo Island",
    "Handlebaristas Box": "Tramonto",
    "East Velo City Alley Box": "Tramonto",
    "PLACEHOLDER_38": "Tramonto",
    "PLACEHOLDER_39": "Tramonto",
    "Farmland City West": "Tramonto",
    "West Velo City Party Pace Guy Box": "Tramonto",
    "Le Grand Crew House Box": "Tramonto",
    "PLACEHOLDER_43": "Tramonto",
    "Farmland Ruins Wall Ramp Box": "Tramonto",
    "Vineyard Between Two Houses Box": "Tramonto",
    "Vineyard Portal Potty Roundabout Box": "Tramonto",
    "Vineyard Secret Track Truck Box": "Tramonto",
    "PLACEHOLDER_48": "Tramonto",
    "PLACEHOLDER_49": "Tramonto",
    "Redwoods Near Biomechanics Guy Box": "Tramonto",
    "PLACEHOLDER_51": "Tramonto",
    "Velo City Near The Corner Kings Box": "Tramonto",
    "Velo City By The Practice Box": "Tramonto",
    "PLACEHOLDER_54": "Tramonto",
    "North Farmland Potty Ramp Box": "Tramonto",
    "Vineyard Redwood Roundabout Box": "Tramonto",
    "Near Cliffhangers Box": "Tramonto",
    "Vineyard Bellshrine Field Ramp Box": "Tramonto",
    "Vineyard Roadside Car and Tent Box": "Tramonto",
    "Gravel Privateers House Box": "Tramonto",
    "Behind The Pedal Pumpers Box": "Tramonto",
    "PLACEHOLDER_62": "Tramonto",
    "PLACEHOLDER_63": "Wasteland",
    "PLACEHOLDER_64": "Wasteland",
    "PLACEHOLDER_65": "Wasteland",
    "PLACEHOLDER_66": "Wasteland",
    "PLACEHOLDER_67": "Wasteland",
    "PLACEHOLDER_68": "Wasteland",
    "PLACEHOLDER_69": "Wasteland",
    "PLACEHOLDER_70": "Wasteland",
    "PLACEHOLDER_71": "Wasteland",
    "PLACEHOLDER_72": "Wasteland",
    "PLACEHOLDER_73": "Wasteland",
    "PLACEHOLDER_74": "Wasteland",
    "PLACEHOLDER_75": "Wasteland",
    "PLACEHOLDER_76": "Wasteland",
    "PLACEHOLDER_77": "Wasteland",
    "PLACEHOLDER_78": "Wasteland",
    "PLACEHOLDER_79": "Wasteland",
    "PLACEHOLDER_80": "Wasteland",
    "PLACEHOLDER_81": "Wasteland",
    "PLACEHOLDER_82": "Wasteland",
    "PLACEHOLDER_83": "Wasteland",
    "PLACEHOLDER_84": "Wasteland",
    "PLACEHOLDER_85": "Wasteland",
    "PLACEHOLDER_86": "Wasteland",
    "PLACEHOLDER_87": "Wasteland",
    "PLACEHOLDER_88": "Wasteland",
    "PLACEHOLDER_89": "Wasteland",
    "PLACEHOLDER_90": "Wasteland",
    "PLACEHOLDER_91": "Wasteland",
    "PLACEHOLDER_92": "Wasteland",
    "PLACEHOLDER_93": "Wasteland",
    "PLACEHOLDER_94": "Wasteland",
    "PLACEHOLDER_95": "Wasteland",
    "PLACEHOLDER_96": "Wasteland",
    "PLACEHOLDER_97": "Wasteland",
    "PLACEHOLDER_98": "Mount Send",
    "PLACEHOLDER_99": "Mount Send",
    "Corp shop - Part #1": "Wasteland",
    "Corp shop - Part #2": "Wasteland",
    "Corp shop - Part #3": "Wasteland",
    "Corp shop - Part #4": "Wasteland",
    "Corp shop - Part #5": "Wasteland",
    "Corp shop - Part #6": "Wasteland",
    "Corp shop - Part #7": "Wasteland",
    "Corp shop - Part #8": "Wasteland",
    "Corp shop - Part #9": "Wasteland",
    "Corp shop - Part #10": "Wasteland",
    "Corp shop - Part #11": "Wasteland",
    "Corp shop - Part #12": "Wasteland",
    "Junkyard govt shop - Part #1": "Wasteland",
    "Junkyard govt shop - Part #2": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #1": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #2": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #3": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #4": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #5": "Wasteland",
    "Wasteland Shop (Flea) Variant - Part #6": "Wasteland",
    "Sequoias Govt Shop - Part #1": "Tramonto",
    "Sequoias Govt Shop - Part #2": "Tramonto",
    "Sequoias Govt Shop - Part #3": "Tramonto",
    "Sequoias Govt Shop - Part #4": "Tramonto",
    "Vineyards coast shop - Part #1": "Tramonto",
    "Vineyards coast shop - Part #2": "Tramonto",
    "Vineyards coast shop - Part #3": "Tramonto",
    "Vineyards coast shop - Part #4": "Tramonto",
    "Vineyards coast shop - Part #5": "Tramonto",
    "Vineyards coast shop - Part #6": "Tramonto",
    "Vineyards coast shop - Part #7": "Tramonto",
    "Pink Shop - Part #1": "Tramonto",
    "Pink Shop - Part #2": "Tramonto",
    "Pink Shop - Part #3": "Tramonto",
    "Pink Shop - Part #4": "Tramonto",
    "Pink Shop - Part #5": "Tramonto",
    "Hot Dog shop - Part #1": "Tramonto",
    "Hot Dog shop - Part #2": "Tramonto",
    "Plant Shop - Part #1": "Tramonto",
    "Plant Shop - Part #2": "Tramonto",
    "Plant Shop - Part #3": "Tramonto",
    "Plant Shop - Part #4": "Tramonto",
    "Entry Plaza Shop - Part #1": "Tramonto",
    "Entry Plaza Shop - Part #2": "Tramonto",
    "Entry Plaza Shop - Part #3": "Tramonto",
    "Hub Shop 2 - Part #1": "Tramonto",
    "Hub Shop 2 - Part #2": "Tramonto",
    "Hub Shop 2 - Part #3": "Tramonto",
    "Hub Shop 2 - Part #4": "Tramonto",
    "Daves bike shop - Part #1": "Tramonto",
    "Daves bike shop - Part #2": "Tramonto",
    "Daves bike shop - Part #3": "Tramonto",
    "Daves bike shop - Part #4": "Tramonto",
    "Daves bike shop - Part #5": "Tramonto",
    "Daves bike shop - Part #6": "Tramonto",
    "Daves bike shop - Part #7": "Tramonto",
    "Daves bike shop - Part #8": "Tramonto",
    "Daves bike shop - Part #9": "Tramonto",
    "Mount Send Shop (Flea) Variant - Part #1": "Mount Send",
    "Mount Send Shop (Flea) Variant - Part #2": "Mount Send",
    "Mount Send Shop (Flea) Variant - Part #3": "Mount Send",
}


class WheelWorldLocation(Location):
    game = "Wheel World"


def create_all_locations(world: WheelWorldWorld) -> None:
    for name, scene in LOCATION_SCENE.items():
        region = world.get_region(scene)
        loc = WheelWorldLocation(world.player, name, LOCATION_NAME_TO_ID[name], region)
        region.locations.append(loc)

    create_events(world)


def create_events(world: WheelWorldWorld) -> None:
    from .items import ITEM_NAME_TO_ID

    beach_box = world.get_location("Lunardo Hill Boys Beach Box")
    commuter_wheel = WheelWorldItem(
        "Commuter Wheel", ItemClassification.progression, ITEM_NAME_TO_ID["Commuter Wheel"], world.player
    )
    beach_box.place_locked_item(commuter_wheel)

    mountain = world.get_region("Mount Send")
    event_location = WheelWorldLocation(world.player, "Perform The Great Shift", None, mountain)
    event_item = WheelWorldItem("Victory", ItemClassification.progression, None, world.player)
    event_location.place_locked_item(event_item)
    mountain.locations.append(event_location)
